TrustTheVote-Project/Rocky-OVR

lib/csv_formatter.rb
lib/report_generator.rb

- datetime values - removed time zone 
- empty values (except strings) -> NULL
- true/false -> 1/0
- everything is quoted
- added header

fixed dump formatting

---

app/models/state_customizations/ca/soap_request.xml.erb

true values for ca test

---

app/validators/registrant_validator.rb

turning back on title requirement as match rate was horrible with it off

require title

---

app/helpers/abr_state_methods/nd.rb
app/views/abrs/_state_fields.html.haml
config/locales/states/en.yml

Updates per Andrew.
**Note** : Includes a small update to core file, added toggleHiddenAny to allow disjunct hiding of a field.
Initially, I modified toggleHidden (not seeing that this required the disjunct function), then I refactored into a completely separate function.
Will be safe as this does not change any existing functionality.

Add nd pdf form

---

app/controllers/abrs_controller.rb

Adds :unit to abr params

---

app/helpers/abr_state_methods/ga.rb

Updates the election date field for proper pdf filling

Update Election Date Field

---

config/locales/states/en.yml

Quick language change per Andrew

Update move date language

---

app/assets/stylesheets/abr-form-fields.scss
app/assets/stylesheets/abr_states/wv.scss
app/helpers/abr_state_methods/wv.rb
config/locales/states/en.yml

Addresses formatting and required alternate mailing addres

Add wv pdf form

---

app/models/geo_state.rb

The fullname select for states

Adds collection_for_select_full_name

---

app/helpers/abr_state_methods/de.rb
config/locales/states/en.yml

Langauge and field changes per Andrew

Update de pdf form

---

app/views/abrs/_state_fields.html.haml

The non-controversial part of the client-side script update.

require visibility toggling fields to be active

---

config/locales/states/en.yml

Removes requirements and language change per Andrew

Update nh pdf

---

app/helpers/abr_state_methods.rb

Don't create/save state attributes till valid

---

app/assets/javascripts/abr_states/al.js
app/helpers/abr_state_methods.rb
app/helpers/abr_state_methods/al.rb
app/views/abrs/_state_fields.html.haml
app/views/layouts/abr.html.erb
config/application.rb
config/locales/states/en.yml

Implements general functions for 
- state specific JS files
- A format error message *pattern* (so I can swap in the state of interest)
... and then the specific requested functionality for state specific RegEx testing on AL DLN field.

Dln validation al

---

app/assets/javascripts/dynamic-nav.js
app/assets/javascripts/validation.js
app/controllers/state_registrants_controller.rb
app/helpers/application_helper.rb
app/models/state_registrants/base.rb
app/models/state_registrants/pa_registrant.rb
app/validators/pa_registrant_validator.rb
app/views/state_registrants/pa/_complete_newui2020.html.haml
app/views/state_registrants/pa/_header.html.haml
app/views/state_registrants/pa/_header_newui2020.html.haml
app/views/state_registrants/pa/_pending_newui2020.html.haml
app/views/state_registrants/pa/_step_2_mobile_newui2020.html.haml
app/views/state_registrants/pa/_step_2_newui2020.html.haml
app/views/state_registrants/pa/_step_3_mobile_newui2020.html.haml
app/views/state_registrants/pa/_step_3_newui2020.html.haml
app/views/state_registrants/pa/_step_4_mobile_newui2020.html.haml
app/views/state_registrants/pa/_step_4_newui2020.html.haml
app/views/state_registrants/pa/complete.html.haml
app/views/state_registrants/pa/pending.html.haml
app/views/state_registrants/pa/step_2.html.haml
app/views/state_registrants/pa/step_2_mobile.html.haml
app/views/state_registrants/pa/step_3.html.haml
app/views/state_registrants/pa/step_3_mobile.html.haml
app/views/state_registrants/pa/step_4.html.haml
app/views/state_registrants/pa/step_4_mobile.html.haml
app/views/step2/_name_only_mobile.html.erb
config/locales/en-newui2020.yml
config/locales/txt/en-newui2020.yml

Desktop should be done; Mobile not, but it looked like quick work before the refactor.

New ui 2020 pa update

---

config/locales/states/en.yml

Hi Alex, can you put these on staging so we can review?

changed 2021 election deadlines to evergreen election deadlines

---

lib/tasks/yaml.rake

```
rails yaml:export > sample.csv
open sample.csv
```

Add rake task to export translations from YAML to CSV

---

config/locales/states/en.yml

AK, FL, HI, IL, IA, NV, NM, NY, NC, OH, SC, WV ID

---

app/mailers/wa_notifier.rb
app/models/state_registrants/wa_registrant.rb
app/views/state_registrant_notifier/wa_confirmation.html.erb
app/views/state_registrants/wa/step_2.html.haml
app/views/state_registrants/wa/step_2_mobile.html.haml
app/views/state_registrants/wa/step_3_mobile.html.haml
config/locales/email/en.yml
config/locales/states/en.yml

Adds:
- DLN instruction text
- WA Thank you email
Debugs mobile display

Final3 requests 06072922

---

app/helpers/abr_state_methods/ks.rb
config/locales/states/en.yml

Dates -> Election dates; 
Fixes middle initial mapping;
Text updates

2022 abr ks 2

---

app/assets/stylesheets/abr-form-fields.scss
config/locales/states/en.yml

This problem came up in MI, but I imagine a general problem, so I addressed in the general css file.

Language/ date label rendering
